const names = [
    'Wioleta Pach',
    'Zofia Stasiak',
    'Cecylia Wydra',
    'Balbina Ochocka',
    'Kinga Piłat',
    'Kalina Krzemien',
    'Olga Moszkowicz',
    'Maryla Jeżewska',
    'Odeta Turek',
    'Noud Groothalle',
    'Teun Ekkerink',
    'Pier Assendorp',
    'Matthijs Mennink',
    'Korneel Septer',
    'Andries IJsak',
    'Freek Vellener',
    'Koen Lokman',
    'Lodewijk Struijck',
    'Stefaan Houtzagers',
    'Buddy Saunders',
    'Dennis Hunter',
    'Alfie Moss',
    'River Lewis',
    'Tomas Stone',
    'Samuel Kelly',
    'Rory Phillips',
    'Thomas Hussain',
    'Ralphy Palmer',
    'Eric Evans',
    'Silver Gardner',
    'Jody Wright',
    'Dane Mills',
    'Sam Mason',
    'Rudy Powell',
    'Carol Griffith',
    'Brynn Witt',
    'Jaden Terrell',
    'Riley Rice',
    'Ash Mcintosh',
    'Rowan Edwards',
    'Ryan Shaw',
    'Riley Harris',
    'Danni Francis',
    'Will Lloyd',
    'Danni Roy',
    'Alex Dean',
    'Bev Gamble',
    'Danny Blair',
    'Leslie Diaz',
    'Sugondo Xiaohui',
    'Ateng Nuwa',
    'Ymkje Anakotta',
    'Merry Situmorang',
    'Jochebed Selangit',
    'Ruby Silo',
    'Raja Nizar',
    'Fida Nicola',
    'Fairuz Jasir',
    'Tarub Jamal',
    'Zainab Sabri',
    'Rima Khalid',
];

const colors = [
    '#9951F5',
    '#7A1BF2',
    '#5F0BC9',
    '#460894',
    '#00E80B',
    '#00C008',
    '#008E06',
    '#FF17D2',
    '#D400AB',
    '#9C007E',
    '#2CC0FF',
    '#00A5EC',
    '#0284CD',
    '#E4B200',
    '#AC8600',
];

export const randomName = () => names[Math.floor(Math.random() * names.length)];
export const randomColor = () => colors[Math.floor(Math.random() * colors.length)];
